### PR TITLE
add 06-unreachable-condition-solution

### LINKED ISSUE #10: Write solution for 06-unreachable-condition.js
`/javascript/challenges/06-unreachable-condition.js` is missing a solution file in `/javascript/solutions`.

### PR DESCRIPTION
**Pull request by ir3ne**
Fix https://github.com/Kornil/whiteboard-programming-challenges/issues/10

### CODE REVIEW

**Comment by Kornil** [comment]
The code provided does not solve the bug. The issue runs a bit deeper than it looks like!

A little help: JavaScript `&&` and `||` operators do not work the same as most other languages.

**Comment by ir3ne** [comment]
@Kornil updated!

**Comment by Kornil** [comment]
Perfect! Just need a little comment on the code explaining how does this code solves the issue.

**Comment by Kornil** [comment]
Good job! Thank you for taking the time to solve this issue. :)

**Pull request merged**
